### ISSUE TITLE
Install pb globally or locally

### ISSUE THREAD

**Issue by agershun** [SheetJS/pb#3]
Thank you for the great tool!

Question: how to install the ```pb``` package: locally or globally?

   npm install -g pb

or it does not matter?

**Comment by SheetJSDev** [comment]
Installing globally is easier, that way you can run from the shell as `pb`

**Comment by agershun** [comment]
Could you add this to the README.md?

**Comment by SheetJSDev** [comment]
@agershun the latest version of the README advocates the global install
